// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCSbFJamYnB1libGN76-XR2vBiSi4xrt7c",
      authDomain: "financepm-a48bd.firebaseapp.com",
      databaseURL: "https://financepm-a48bd-default-rtdb.firebaseio.com",
      projectId: "financepm-a48bd",
      storageBucket: "financepm-a48bd.appspot.com",
      messagingSenderId: "241797545371",
      appId: "1:241797545371:web:978a96b4b8069f2cf6753e",
      measurementId: "G-PSGPLPKYC7"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSbFJamYnB1libGN76-XR2vBiSi4xrt7c',
    appId: '1:241797545371:android:751728e89a4cd219f6753e',
    messagingSenderId: '241797545371',
    projectId: 'financepm-a48bd',
    storageBucket: "financepm-a48bd.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT1zNWpyIsMp29W0OEKcJ9NJa0b_HvDwE',
    appId: '1:736551413173:ios:f50c8a1a94df52472fe5fc',
    messagingSenderId: '736551413173',
    projectId: 'maanpos',
    storageBucket: 'maanpos.appspot.com',
    iosBundleId: 'com.maantheme.mobilepo',
  );
}
